Function New-OpsLogixOracleAlertTemplateInstance
{
<# 
 .Synopsis
  Create a OpsLogix Oracle Alert Rule monitoring template instance in OpsMgr.

 .Description
  Create a OpsLogix Oracle Alert Rule monitoring template instance in OpsMgr using OpsMgr SDK. A boolean value $true will be returned if the monitoring template instance creation has been successful, otherwise, a boolean value of $false is returned if any there are any errors occurred during the creation process.

 .Parameter -SDKConnection
  OpsMgr SDK Connection object (SMA/Azure Automation connection or hash table).

 .Parameter -SDK
  Management Server name

 .Parameter -UserName
  Alternative user name to connect to the management group (optional).

 .Parameter -Password
  Alternative password to connect to the management group (optional).

 .Parameter -MPName
  Name for the unsealed MP of which the OpsLogix Oracle Alert Rule monitoring template instance is going to stored.

 .Parameter -DisplayName
  The OpsLogix Oracle Alert Rule Template instance display name

 .Parameter -Description
  The OpsLogix Oracle Alert Rule Template instance description

 .Parameter -Enabled
  Specify if the Rules and Monitors created by the template are enabled by default. this is a boolean parameter. the default value is set to $true if not specified.

 .Parameter -Query
  Specify the query to be executed by the Opslogix Oracle alert rule

 .Parameter -ReturnColumnName
  Specify the return column name from the query

 .Parameter -Target
  The target class of the alert rule. Possible values are (case insensitive): 'Instance'; 'Control File'; 'Data File'; 'Redo Log group'; 'Redo Log File'; "Table Space"

 .Parameter -LocaleId
  The Locale ID for the language pack items. This is an optional parameter, if not specifiied, the value "ENU" is used.

 .Parameter -QueryInterval
  The query interval in seconds, the default value is 300 (5 minutes) if it is not specified.

 .Parameter -Operator
  Specify the Operator used to evaluate the query returned value. Possible values are (case insensitive): 'Equal'; 'NotEqual'

 .Parameter -TargetValue
  Specify the target value used to evaluate the query result.

 .Parameter -AlertName
  The name of the alert generated by the rule

 .Parameter -AlertDescription
  The description of the alert generated by the rule

 .Parameter -AlertPriority
  The priority of the alert generated by the rule. Possible values are (case insensitive): 'Low'; 'Medium'; 'High'. the default value is 'Medium' if not specified.

 .Parameter -AlertSeverity
  The severity of the alert generated by the rule. Possible values are (case insensitive): 'Information'; 'Warning'; 'Critical'. the default value is 'Warning' if not specified.

 .Parameter -IncreaseMPVersion
  Increase MP version by 0.0.0.1 (Increase revision by 1).

 .Example
  # Connect to OpsMgr management group via management server "OpsMgrMS01" and then create an OpsLogix Oracle Alert Rule template instance with the following properties:
   $parms = @{
        SDK = "OpsMgrMS01";
        UserName = "domain\SCOM.Admin"
        Password = $(ConvertTo-SecureString -AsPlainText "password1234" -force);
        MPName = "TYANG.Lab.Test";
        DisplayName = "Test Oracle Alert rule";
        Description = "This is a test instance for the OpsLogix Oracle alert rule template";
        Enabled = $true;
        Query = 'select count(*) "Order_COUNT" from sys.orders';
        ReturnColumnName = "Order_COUNT";
        Target="Instance";
        QueryInterval = 300;
        Operator = "Equal";
        TargetValue = 0;
        AlertName= "Order Table Has no rows";
        AlertDescription = "please refer check the order table, it is empty.";
        AlertPriority = "Medium";
        AlertSeverity = "Critical"
   }
  
  New-OpsLogixOracleAlertTemplateInstance @parms
#>
    [CmdletBinding()]
    PARAM (
        [Parameter(ParameterSetName='SMAConnection',Mandatory=$true,HelpMessage='Please specify the SMA Connection object')][Alias('Connection','c')][Object]$SDKConnection,
		[Parameter(ParameterSetName='IndividualParameter',Mandatory=$true,HelpMessage='Please enter the Management Server name')][Alias('DAS','Server','s')][String]$SDK,
        [Parameter(ParameterSetName='IndividualParameter',Mandatory=$false,HelpMessage='Please enter the user name to connect to the OpsMgr management group')][Alias('u')][String]$Username = $null,
        [Parameter(ParameterSetName='IndividualParameter',Mandatory=$false,HelpMessage='Please enter the password to connect to the OpsMgr management group')][Alias('p')][SecureString]$Password = $null,
        [Parameter(Mandatory=$true,HelpMessage='Please enter management pack name')][ValidateNotNullOrEmpty()][String]$MPName,
        [Parameter(Mandatory=$true,HelpMessage='Please enter Template Instance Display Name')][ValidateNotNullOrEmpty()][String]$DisplayName,
        [Parameter(Mandatory=$true,HelpMessage='Please enter Template Instance description')][String]$Description,
        [Parameter(Mandatory=$false,HelpMessage='Please specify if the rule is enabled by default')][Boolean]$Enabled=$true,
        [Parameter(Mandatory=$true,HelpMessage='Please enter the query executed by the alert rule')][ValidateNotNullOrEmpty()][String]$Query,
        [Parameter(Mandatory=$true,HelpMessage='Please enter the return column name')][ValidateNotNullOrEmpty()][String]$ReturnColumnName,
        [Parameter(Mandatory=$true,HelpMessage='Please select target class of the alert rule')][ValidateSet('Instance', 'Control File', 'Data File', 'Redo Log group', 'Redo Log File', 'Table Space')][String]$Target,
        [Parameter(Mandatory=$false,HelpMessage='Please enter the Management Pack Locale ID')][ValidateNotNullOrEmpty()][String]$LocaleId="ENU",
        [Parameter(Mandatory=$false,HelpMessage='Please enter the query interval (in seconds)')][Int]$QueryInterval=300,
        [Parameter(Mandatory=$true,HelpMessage='Please select the operator')][ValidateSet('Equal', 'NotEqual')][String]$Operator,
        [Parameter(Mandatory=$true,HelpMessage='Please enter the target value that will be used in the alert criteria')][Int]$TargetValue,
        [Parameter(Mandatory=$true,HelpMessage='Please enter the alert name')][ValidateNotNullOrEmpty()][String]$AlertName,
        [Parameter(Mandatory=$true,HelpMessage='Please enter the alert description')][ValidateNotNullOrEmpty()][String]$AlertDescription,
        [Parameter(Mandatory=$true,HelpMessage='Please specify the alert priority')][ValidateSet('Low', 'Medium', 'High')][String]$AlertPriority,
        [Parameter(Mandatory=$true,HelpMessage='Please specify the alert severity')][ValidateSet('Information', 'Warning', 'Critical')][String]$AlertSeverity,
        [Parameter(Mandatory=$false,HelpMessage='Increase MP version by 0.0.0.1')][Boolean]$IncreaseMPVersion = $false
    )

    #Connect to MG
	If ($SDKConnection)
	{
		Write-Verbose "Connecting to Management Group via SDK $($SDKConnection.ComputerName)`..."
		$MG = Connect-OMManagementGroup -SDKConnection $SDKConnection
		$SDK = $SDKConnection.ComputerName
		$Username = $SDKConnection.Username
		$Password= ConvertTo-SecureString -AsPlainText $SDKConnection.Password -force
	} else {
		Write-Verbose "Connecting to Management Group via SDK $SDK`..."
		If ($Username -and $Password)
		{
			$MG = Connect-OMManagementGroup -SDK $SDK -UserName $Username -Password $Password
		} else {
			$MG = Connect-OMManagementGroup -SDK $SDK
		}
	}

    #Get the unsealed MP
    Write-Verbose "Getting destination MP '$MPName'..."
    $strMPquery = "Name = '$MPName'"
    $mpCriteria = New-Object  Microsoft.EnterpriseManagement.Configuration.ManagementPackCriteria($strMPquery)
    $MP = $MG.ManagementPacks.GetManagementPacks($mpCriteria)[0]

    If ($MP)
    {
        #MP found, now check if it is sealed
        Write-Verbose "Found destination MP '$MPName', the MP display name is '$($MP.DisplayName)'. MP Sealed: $($MP.Sealed)"
        If ($MP.sealed)
        {
            Write-Error 'Unable to save to the management pack specified. It is sealed. Please specify an unsealed MP.'
            return $false
        }
    } else {
        Write-Error 'The management pack specified cannot be found. please make sure the correct name is specified.'
        return $false
    }

    #Translate alert severity and priority
    Switch ($AlertPriority.ToLower())
    {
        "low" {$iAlertPriority = 0}
        "medium" {$iAlertPriority = 1}
        "high" {$iAlertPriority = 2}
    }

    Switch ($AlertSeverity.ToLower())
    {
        "information" {$iAlertSeverity = 0}
        "warning" {$iAlertSeverity = 1}
        "critical" {$iAlertSeverity = 2}
    }

    #Get the target class
    Switch ($Target.ToLower())
    {
        'instance' {$TargetClass = 'OpsLogix.IMP.Oracle.Instance'}
        'control file' {$TargetClass = 'OpsLogix.IMP.Oracle.ControlFile'}
        'data file' {$TargetClass = 'OpsLogix.IMP.Oracle.DataFile'}
        'redo log group' {$TargetClass = 'OpsLogix.IMP.Oracle.RedoLogGroup'}
        'redo log file' {$TargetClass = 'OpsLogix.IMP.Oracle.RedoLogFile'}
        'table space' {$TargetClass = 'OpsLogix.IMP.Oracle.TableSpace'}
    }


    #Get the template
    Write-Verbose "Getting the OpsLogix Oracle Alert Rule monitoring template..."
    $strTemplatequery = "Name = 'OpsLogix.IMP.Oracle.Config.2012.Alert.Rule.Template'"
    $TemplateCriteria = New-object Microsoft.EnterpriseManagement.Configuration.ManagementPackTemplateCriteria($strTemplatequery)
    $OpsLogixOracleAlertTemplate = $MG.GetMonitoringTemplates($TemplateCriteria)[0]
    if (!$OpsLogixOracleAlertTemplate)
    {
        Write-Error "The Opslogix Oracle Alert Rule Monitoring Template cannot be found. please make sure the OpsLogix Oracle management packs are imported into your management group."
        return $false
    }

    #Generate template instance configuration
    $NewGUID = [GUID]::NewGuid().ToString().Replace("-","")
    $NameSpace = "OpsLogixOracleAlertTemplate_$NewGUID"
    $StringBuilder = New-Object System.Text.StringBuilder
    $configurationWriter = [System.Xml.XmlWriter]::Create($StringBuilder)
    $configurationWriter.WriteStartElement("Configuration");
    $configurationWriter.WriteElementString("Name", $DisplayName);
    $configurationWriter.WriteElementString("Description", $Description);
    $configurationWriter.WriteElementString("LocaleId", $LocaleId);
    $configurationWriter.WriteElementString("NameSpace", $NameSpace);
    $configurationWriter.WriteElementString("Enabled", $Enabled.ToString().ToLower());
    $configurationWriter.WriteElementString("HostReference", "");
    $configurationWriter.WriteElementString("ManagementPack", $MPName);
    
    $configurationWriter.WriteElementString("ColumnName", $ReturnColumnName);
    $configurationWriter.WriteElementString("Query", $Query);
    $configurationWriter.WriteElementString("IntervalSeconds", $QueryInterval);
    $configurationWriter.WriteElementString("Target", $TargetClass);
    $configurationWriter.WriteElementString("TargetValue", $TargetValue);
    $configurationWriter.WriteElementString("Operator", $Operator);
    $configurationWriter.WriteElementString("AlertName", $AlertName);
    $configurationWriter.WriteElementString("AlertDescription", $AlertDescription);
    $configurationWriter.WriteElementString("AlertPriority", $iAlertPriority);
    $configurationWriter.WriteElementString("AlertSeverity", $iAlertSeverity);
    $configurationWriter.WriteEndElement();
    $configurationWriter.Flush();
    $XmlWriter = New-Object Microsoft.EnterpriseManagement.Configuration.IO.ManagementPackXmlWriter([System.Xml.XmlWriter]::Create($StringBuilder))
    $strConfiguration = $StringBuilder.ToString()
    Write-Verbose "Template Instance Configuration:"
    Write-Verbose $strConfiguration
    #Create the template instance
    Write-Verbose "Creating the OpsLogix Oracle Alert Rule template instance on management pack '$MPName'..."
    Try {
        [Void]$MP.ProcessMonitoringTemplate($OpsLogixOracleAlertTemplate, $strConfiguration, "TemplateoutputOpsLogixIMPOracleConfig2012AlertRuleTemplate$NewGUID", $DisplayName, $Description)
    } Catch {
        Write-Error $_.Exception.InnerException
        Return $False
    }
    #Increase MP version
    If ($IncreaseMPVersion)
    {
        Write-Verbose "the version of managemnet pack '$MPVersion' will be increased by 0.0.0.1"
        $CurrentVersion = $MP.Version.Tostring()
        $vIncrement = $CurrentVersion.Split('.')
        $vIncrement[$vIncrement.Length - 1] = ([System.Int32]::Parse($vIncrement[$vIncrement.Length - 1]) + 1).ToString()
        $NewVersion = ([System.String]::Join('.', $vIncrement))
        $MP.Version = $NewVersion
    }

    #Verify and save the monitor
    Try {
        $MP.verify()
        $MP.AcceptChanges()
        $Result = $true
		Write-Verbose "OpsLogix Oracle Alert Rule template instance '$DisplayName' successfully created in Management Pack '$MPName'($($MP.Version))."
    } Catch {
        $Result = $false
		$MP.RejectChanges()
        Write-Error "Unable to create OpsLogix Oracle Alert Rule template instance '$DisplayName' in management pack $MPName."
    }
    $Result
}